version: '3.8'
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PSQL_PWD}
      POSTGRES_USER: ${PSQL_USR}
      POSTGRES_DB: ${PSQL_DB}
    hostname: db    
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USR}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  backend:
    build: "./backend"
    hostname: backend
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/${PSQL_DB}"
      - "spring.datasource.username=${PSQL_USR}"
      - "spring.datasource.password=${PSQL_PWD}"
      - "spring.datasource.driver-class-name=org.postgresql.Driver"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 30s
      retries: 4
      start_period: 30s
      timeout: 30s
    depends_on:
      db:
        condition: service_healthy      

  frontend:
    build: "./frontend"
    hostname: frontend
    ports:
      - "4200:80"
    networks:
      - frontend
    depends_on:
      backend:
        condition: service_healthy

networks:
  frontend: 
    driver: bridge
  backend: 
    driver: bridge